### ISSUE TITLE
Link to download the SynthTabNet dataset is not working

### ISSUE THREAD

**Issue by HarshRao1905** [IBM/SynthTabNet#17]
Links to download the Fintabnet, Marketing, PubTabNet, Sparse dataset is not working. Getting the error attached.
![error](https://github.com/IBM/SynthTabNet/assets/113628302/9eae0d03-7dc7-47d1-9b37-10e812e43080)

**Comment by nikos-livathinos** [comment]
Now the links should work.

Thank you for bringing it up!
