### ISSUE TITLE
Enquiry regarding Table 2 results of the paper

### ISSUE THREAD

**Issue by mckhang** [IBM/SynthTabNet#20]
Hi, first-of-all thanks for publishing the dataset of your great work!

I would like to enquire about the results on Table 2 of the paper.
Q: For results on PubTabNet (PTN) dataset, was the model evaluated against the validation dataset or the test dataset ?
In Figure 7 (Supplementary material), it can be seen that bar-information for PubTabNet only displays Train and Val, making one wonder if all evaluations done against PTN were on the validation dataset.

Thank you

**Comment by nassarofficial** [comment]
Thanks you! Sorry for the confusion, but the results are on the "test" split. The The split was released by PTN authors towards end of submission.
