### ISSUE TITLE
Invalid json error

### ISSUE THREAD

**Issue by aishniparab** [IBM/SynthTabNet#24]
I am using json lines to load data from fintabnet_synthetic_data.jsonl. It appears that for several images, the annotation json is badly formatted. Is anyone else having this issue?

**Comment by gjgjh** [comment]
> I am using json lines to load data from fintabnet_synthetic_data.jsonl. It appears that for several images, the annotation json is badly formatted. Is anyone else having this issue?

I encountered the same problem. How did you solved this?
