### ISSUE TITLE
Simple question about TableFormer evaluation TEDS score

### ISSUE THREAD

**Issue by ejlee95** [IBM/SynthTabNet#9]
Hi, thanks for publishing your dataset!

I have a question about the paper, TableFormer.

In Table 2 in the paper, you wrote TEDS scores of the methods.
Did you include 'content' when evaluating the scores or not?

**Comment by nassarofficial** [comment]
Thanks for reaching out! As mentioned in the paper Table 2 is only structural. Table 4 includes content, but only compared to methods EDD and methods that depend on PDFs.
